apiVersion: v1
kind: ConfigMap
metadata:
  name: poc-postgress-configmap-seed
  annotations:
data:
  data_seed.sql: |
    CREATE TYPE process_status AS ENUM ('unprocessed', 'in_progress', 'processed');

    CREATE TABLE IF NOT EXISTS fracture_incidents (
      id SERIAL PRIMARY KEY,
      patient_name VARCHAR(50),
      incident_date VARCHAR(50),
      incident_location VARCHAR(255),
      patient_complaints TEXT,
      description TEXT NOT NULL,
      scan_image VARCHAR(50) NOT NULL,
      fracture_classification VARCHAR(50),
      incident_status process_status DEFAULT 'unprocessed'
    );

    INSERT INTO fracture_incidents (description, scan_image)
    VALUES 
        ('Op 27 augustus 2024 omstreeks 14:30 uur heeft er een ongeval plaatsgevonden op de fietsroute langs de Schouwseweg, vlakbij het park aan de rand van het dorp. De betrokken persoon, Mark Jansen, een 35-jarige man, is gevallen terwijl hij op zijn fiets reed. Bij aankomst van de hulpdiensten klaagde Mark over ernstige pijn in zijn zij en had hij moeite met ademhalen. Er zijn geen verdere details over de aard van de verwondingen op dit moment, maar de hulpdiensten hebben hem met spoed naar het ziekenhuis vervoerd voor nader onderzoek en behandeling.', 'incident_0001'),
    ('Vandaag, op 28 augustus 2024 omstreeks 11:15 uur, heeft er een ongeval plaatsgevonden voor het plaatselijke café aan de Hoofdstraat 45. De betrokken persoon is Lisa de Vries, een 42-jarige vrouw. Lisa was bezig met het uitladen van boodschappen uit haar auto toen een voorbijrijdende bestelwagen haar aanstootte. Bij aankomst van de hulpdiensten bleek Lisa ernstige pijn in haar onderrug en nek te hebben. Ze had ook moeite met bewegen en klaagde over duizeligheid. De hulpdiensten hebben ter plaatse eerste hulp verleend en Lisa is met spoed naar het ziekenhuis gebracht voor nader onderzoek en behandeling. De exacte aard van haar verwondingen wordt nog vastgesteld.', 'incident_0002'),
    ('Op 29 augustus 2024 omstreeks 16:45 uur heeft er een ongeval plaatsgevonden op het parkeerterrein bij Winkelcentrum De Zonnebaan. De betrokken persoon is Tom Peters, een 29-jarige man. Tom was bezig met het inladen van zijn winkelmand in zijn auto toen hij uitgleed op een natte plek op het asfalt en hard tegen de autodeur viel. Bij aankomst van de hulpdiensten klaagde Tom over scherpe pijn in zijn schouder en had hij moeite met bewegen. De hulpdiensten hebben ter plaatse eerste hulp verleend en Tom is met spoed naar het ziekenhuis vervoerd voor verder onderzoek en behandeling. Het is momenteel niet duidelijk hoe ernstig de verwondingen zijn.', 'incident_0003');