apiVersion: v1
kind: ConfigMap
metadata:
  name: poc-postgress-configmap-seed-demo
  annotations:
data:
  data_seed.sql: |
    CREATE TYPE process_status AS ENUM ('unprocessed', 'in_progress', 'processed');

    CREATE TABLE IF NOT EXISTS fracture_incidents (
      id SERIAL PRIMARY KEY,
      patient_name VARCHAR(50),
      incident_date VARCHAR(50),
      incident_location VARCHAR(255),
      patient_complaints TEXT,
      advice TEXT,
      description TEXT NOT NULL,
      scan_image VARCHAR(50) NOT NULL,
      fracture_classification VARCHAR(50),
      incident_status process_status DEFAULT 'unprocessed'
    );

    INSERT INTO fracture_incidents (description, scan_image, incident_status, patient_name, incident_date, incident_location, patient_complaints, advice, fracture_classification)
    VALUES 
    ('On March 18, 2024, at approximately 2:00 PM, an incident happened during a soccer match at Greenfield Sports Complex. Michael Adams, a 22-year-old player, collided with another player while attempting to block a shot. He fell awkwardly, and upon arrival of the medics, Michael complained of severe pain in his right arm, which appeared to be deformed. Suspecting a fracture, he was quickly taken off the field and driven to the hospital for further assessment and treatment.', 'incident_1.jpg', 'unprocessed', NULL, NULL, NULL, NULL, NULL, NULL),

    ('On December 5, 2024, around 9:00 AM, a workplace accident occurred at the Northside Warehouse. James Miller, a 38-year-old forklift operator, accidentally slipped on a wet surface while loading pallets. He fell, landing hard on his shoulder. When emergency responders arrived, James was in severe pain and unable to move his left arm. Fearing a potential fracture, he was promptly taken to the hospital for further diagnosis and treatment.', 'incident_2.jpg', 'unprocessed', NULL, NULL, NULL, NULL, NULL, NULL),

    ('On April 27, 2024, at approximately 4:20 PM, an incident took place on the hiking trail at Silver Creek Park. Olivia Bennett, a 30-year-old woman, was walking her dog when she tripped over a tree root and fell. When paramedics reached her, Olivia was in considerable pain and could not put weight on her right ankle, which was swollen and bruised. Suspecting a fracture, the medics carefully transported her to the nearest hospital for a thorough examination.', 'incident_3.jpg', 'unprocessed', NULL, NULL, NULL, NULL, NULL, NULL);
