---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: poc-postgress-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
---
kind: Secret
apiVersion: v1
metadata:
  name: poc-postgress-secret
stringData:
  postgress_database: incidents
  postgress_password: password
  postgress_user: dev
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: bram-terlouw-dev
  name: poc-postgress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-postgress
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: poc-postgress
    spec:
      volumes:
        - name: postgress-data
          persistentVolumeClaim:
            claimName: poc-postgress-pvc
      containers:
        - name: postgress
          image: registry.redhat.io/rhel9/postgresql-13:latest
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
            requests:
              cpu: 20m
              memory: 100Mi
          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - '--live'
            initialDelaySeconds: 120
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: poc-postgress-secret
                  key: postgress_user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: poc-postgress-secret
                  key: postgress_password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: poc-postgress-secret
                  key: postgress_database
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: postgress-data
              mountPath: /var/lib/pgsql/data
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          terminationMessagePath: /dev/termination-log
      securityContext:
        capabilities: {}
        privileged: false
  strategy:
    type: Recreate
---
kind: Service
apiVersion: v1
metadata:
  namespace: bram-terlouw-dev
  name: poc-postgress-service
spec:
  ports:
  - name: api
    protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: poc-postgress
  sessionAffinity: None
  type: ClusterIP