---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: poc-minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
---
kind: Secret
apiVersion: v1
metadata:
  name: poc-minio-credentials
stringData:
  minio_root_user: minio
  minio_root_password: minio123
---
kind: Deployment
apiVersion: apps/v1
metadata:
  # namespace: poc-minio
  name: poc-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-minio
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: poc-minio
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: poc-minio-pvc
      containers:
        - name: minio
          image: quay.io/minio/minio:RELEASE.2023-06-19T19-52-50Z
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
            requests:
              cpu: 20m
              memory: 100Mi
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: poc-minio-credentials
                  key: minio_root_user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: poc-minio-credentials
                  key: minio_root_password
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: minio
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          terminationMessagePath: /dev/termination-log
          args:
            - server
            - /data
            - --console-address
            - :9090
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  # namespace: poc-minio
  name: poc-minio-service
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: ui
      protocol: TCP
      port: 9090
      targetPort: 9090
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: poc-minio
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  # namespace: poc-minio
  name: poc-minio-api-route
spec:
  to:
    kind: Service
    name: poc-minio-service
    weight: 100
  port:
    targetPort: api
  wildcardPolicy: None
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  # namespace: poc-minio
  name: poc-minio-ui-route
spec:
  to:
    kind: Service
    name: poc-minio-service
    weight: 100
  port:
    targetPort: ui
  wildcardPolicy: None
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect