---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: poc-minio
  name: poc-minio-job-seed-images
spec:
  backoffLimit: 4
  template:
    spec:
      initContainers:
      - name: wait-for-minio
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z -v -w30 $MINIO_ENDPOINT 9000; do echo "Waiting for Minio connection..."; sleep 2; done;']
        env:
        - name: MINIO_ENDPOINT
          value: poc-minio.svc.cluster.local
      containers:
      - name: add-images-to-bucket
        image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-generic-data-science-notebook:1.2
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args:
        - -ec
        - |-
          git clone https://github.com/BramTerlouw/Beroepsproduct.git

          cat << 'EOF' | python3
          import boto3, os, botocore

          s3 = boto3.client("s3",
                            endpoint_url=os.getenv("AWS_S3_ENDPOINT"),
                            aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
                            aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"))

          # Upload original images to minio
          for filename in os.listdir("Data/incidents_images"):
              with open(f"Data/incidents_images/{filename}", "rb") as f:
                  s3.upload_fileobj(f, "images", f"incidents/{filename}")

          # Upload processed images to minio
          for filename in os.listdir("Data/Training_images"):
              with open(f"Data/Training_images/{filename}", "rb") as f:
                  s3.upload_fileobj(f, "images", f"train/{filename}")

          EOF
        envFrom:
        - secretRef:
            name: secret-minio
      restartPolicy: Never